CREATE TABLE [calendar].[Timezone](
	[Id] [uniqueidentifier] NOT NULL CONSTRAINT [DF_Timezone_Id]  DEFAULT (newsequentialid()),
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Timezone] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]